pipeline {
    agent any
    stages {
        stage('start') {
            steps {
                echo 'starting the process papo'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -Denforcer.skip=true -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Denforcer.skip=true test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Complete') {
            steps {
                echo 'The process has finish'
            }
        }
        
    }
}
